source 'https://rubygems.org'
ruby '2.4.2'

# Native Rails gems — (These are required).
gem 'rails', '4.2.10'
gem 'railties', '4.2.10'
gem 'activemodel', '4.2.10'
gem 'protected_attributes'

# Database Gems
gem 'pg', '0.18.4'

# Webserver Gems
gem 'newrelic_rpm'
gem 'rack-cors'
gem "passenger", ">= 5.0.25", require: "phusion_passenger/rack_handler"

# API helpers
gem "jbuilder"
gem "yajl-ruby"

# Backend Helpers
gem 'bcrypt', :require => "bcrypt"

group :production do
  gem 'rack-timeout'
end

group :development do
  gem 'binding_of_caller'
  gem 'better_errors'
  gem "brakeman", :require => false
end

group :test do
  gem 'rspec'
end

group :development, :test do
  gem 'pry'
end
